import "./globals.css"
import { ReduxProvider } from "@/redux/provider"

  

export const metadata = {
  title: 'Mazeon',
  description: 'Generated by Next.js',
  icons : {
    icon : ['/favicon.ico>v=4'],
    apple : ['/apple-touch-icon.png?v=4'],
    shortcut : ['/apple-touch-icon.png']
  }
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className="bg-body">
        <ReduxProvider>
          {children}
        </ReduxProvider>
        </body>
    </html>
  )
}
